skel = {
	"race": {
		".": "",
		"human": {
			".": "1",
			"race": ["human",],
			"skin": ["white","yellow","red","olive","brown","black",],
			"hair": ["white","blond","red","brown","black",],
			"eyes": ["gray","blue","green","yellow","hazel","brown",],
			"lastname": ["SMITH","JOHNSON","WILLIAMS","BROWN","JONES","MILLER","DAVIS","GARCIA","RODRIGUEZ","WILSON","MARTINEZ","ANDERSON","TAYLOR",
				"THOMAS","HERNANDEZ","MOORE","MARTIN","JACKSON","THOMPSON","WHITE","LOPEZ","LEE","GONZALEZ","HARRIS","CLARK","LEWIS","ROBINSON",
				"WALKER","PEREZ","HALL","YOUNG","ALLEN","SANCHEZ","WRIGHT","KING","SCOTT","GREEN","BAKER","ADAMS","NELSON","HILL","RAMIREZ",
				"CAMPBELL","MITCHELL","ROBERTS","CARTER","PHILLIPS","EVANS","TURNER","TORRES",],
			"nickname": ["",],
			"gender": {
				".": "",
				"neutral": {
					"gender": ["neutral",],
					"firstname": ["Liam","Noah","William","James","Logan","Benjamin","Mason","Elijah","Oliver","Jacob","Lucas","Michael",
						"Alexander","Ethan","Daniel","Matthew","Aiden","Henry","Joseph","Jackson","Samuel","Sebastian","David","Carter",
						"Penelope","Riley","Layla","Lillian","Nora","Zoey","Mila","Aubrey","Hannah","Lily","Addison","Eleanor",],
					".": "2",
				},
				"variable": {
					"gender": ["variable",],
					"firstname": ["Emma","Olivia","Ava","Isabella","Sophia","Mia","Charlotte","Amelia","Evelyn","Abigail","Harper",
						"Emily","Elizabeth","Avery","Sofia","Ella","Madison","Scarlett","Victoria","Aria","Grace","Chloe","Camila",
						"Wyatt","Jayden","John","Owen","Dylan","Luke","Gabriel","Anthony","Isaac","Grayson","Jack",],
					".": "2",
				},
				"feminine": {
					"gender": ["feminine",],
					"firstname": ["Emma","Olivia","Ava","Isabella","Sophia","Mia","Charlotte","Amelia","Evelyn","Abigail","Harper",
						"Emily","Elizabeth","Avery","Sofia","Ella","Madison","Scarlett","Victoria","Aria","Grace","Chloe","Camila",
						"Penelope","Riley","Layla","Lillian","Nora","Zoey","Mila","Aubrey","Hannah","Lily","Addison","Eleanor",],
					".": "4",
				},
				"masculine": {
					"gender": ["masculine",],
					"firstname": ["Liam","Noah","William","James","Logan","Benjamin","Mason","Elijah","Oliver","Jacob","Lucas","Michael",
						"Alexander","Ethan","Daniel","Matthew","Aiden","Henry","Joseph","Jackson","Samuel","Sebastian","David","Carter",
						"Wyatt","Jayden","John","Owen","Dylan","Luke","Gabriel","Anthony","Isaac","Grayson","Jack",],
					".": "4",
				},
			},
			"sex": {
				".": "",
				"none": {
					".": "5",
					"sex": ["none",],
				},
				"all": {
					".": "5",
					"sex": ["all",],
				},
				"male": {
					".": "45",
					"sex": ["male",],
				},
				"female": {
					".": "45",
					"sex": ["female",],
				},
			},
			"age": {
				".": "",
				"venerable": {
					".": "1",
					"age": ["venerable",],
					"level": "9-15",
					"weight": "1.3-1.7",
					"height": "50-60",
					"years": "90-120",
					"hp": "6-15",
					"dex": "6-12",
					"int": "10-18",
					"chr": "10-18",
					"wis": "10-18",
					"str": "4-8",
					"con": "4-8",
				},
				"old": {
					".": "3",
					"weight": "0.9-1.8",
					"level": "5-10",
					"age": ["old",],
					"height": "45-60",
					"years": "60-90",
					"hp": "15-30",
					"dex": "7-15",
					"int": "8-16",
					"chr": "8-16",
					"wis": "8-16",
					"str": "7-15",
					"con": "7-15",
				},
				"middle": {
					".": "7",
					"weight": "1.1-2.0",
					"level": "7-10",
					"age": ["middle",],
					"height": "50-65",
					"years": "45-60",
					"hp": "12-21",
					"dex": "8-16",
					"int": "8-16",
					"chr": "8-16",
					"wis": "8-16",
					"str": "8-16",
					"con": "8-16",
				},
				"adult": {
					".": "10",
					"weight": "1.3-2.2",
					"level": "2-5",
					"age": ["adult",],
					"height": "55-70",
					"years": "20-45",
					"hp": "6-15",
					"dex": "8-16",
					"int": "8-16",
					"chr": "8-16",
					"wis": "8-16",
					"str": "8-16",
					"con": "8-16",
				},
				"youth": {
					".": "11",
					"weight": "1.3-2.2",
					"level": "1-2",
					"age": ["youth",],
					"height": "55-70",
					"years": "10-20",
					"hp": "3-8",
					"dex": "8-16",
					"int": "8-16",
					"chr": "8-16",
					"wis": "8-16",
					"str": "8-16",
					"con": "8-16",
				},
				"child": {
					".": "11",
					"weight": "1-1.3",
					"level": "1-1",
					"age": ["child",],
					"height": "37-54",
					"years": "3-10",
					"hp": "1-3",
					"dex": "3-9",
					"int": "2-8",
					"chr": "4-12",
					"wis": "1-5",
					"str": "1-5",
					"con": "1-5",
				},
				"baby": {
					".": "9",
					"weight": "0.4-1",
					"level": "1-1",
					"age": ["baby",],
					"height": "19-36",
					"years": "0-3",
					"hp": "1-1",
					"dex": "1-1",
					"int": "1-1",
					"chr": "1-1",
					"wis": "1-1",
					"str": "1-1",
					"con": "1-1",
				},
			},
		},
		"dwarf": {
			".": "1",
			"race": ["dwarf",],
			"skin": ["red","olive","brown","tan",],
			"hair": ["gray","red","brown","black",],
			"eyes": ["gray","green","hazel","brown",],
			"speed": "25",
			"lastname": ["Balderk", "Battlehammer", "Brawnanvil", "Dankil", "Fireforge", "Frostbeard", "Gorunn", "Holderhek", "Ironfist", 
				"Loderr", "Lutgehr", "Rumnaheim", "Strakeln", "Torunn", "Ungart",],
			"nickname": ["",],
			"alignments": {
				".": "",
				"lg": {".": "1", "alignment": ["lawful good",],},
				"ng": {".": "2", "alignment": ["neutral good",],},
				"cg": {".": "3", "alignment": ["chaotic good",],},
				"ln": {".": "2", "alignment": ["lawful neutral",],},
				"nn": {".": "2", "alignment": ["neutral neutral",],},
				"cn": {".": "2", "alignment": ["chaotic neutral",],},
				"le": {".": "3", "alignment": ["lawful evil",],},
				"ne": {".": "2", "alignment": ["neutral evil",],},
				"ce": {".": "1", "alignment": ["chaotic evil",],},
			},
			"gender": {
				".": "",
				"neutral": {
					"gender": ["neutral",],
					"firstname": ["Adrik", "Alberich", "Baern", "Barendd", "Brottor", "Bruenor", "Dain", "Darrak", "Delg", "Eberk", 
						"Gurdis", "Helja", "Hlin", "Kathra", "Kristryd", "Ilde", "Liftrasa", "Mardred", "Riswynn", "Sannl", "Torbera", "Torgga", 
						"Vistra",],
					".": "2",
				},
				"variable": {
					"gender": ["variable",],
					"firstname": ["Amber", "Artin", "Audhild", "Bardryn", "Dagnal", "Diesa", "Eldeth", "Falkrunn", "Finellen", "Gunnloda", 
						"Taklinn", "Thoradin", "Thorin", "Tordek", "Traubon", "Travok", "Ulfgar", "Veit", "Vondal"],
					".": "2",
				},
				"feminine": {
					"gender": ["feminine",],
					"firstname": ["Amber", "Artin", "Audhild", "Bardryn", "Dagnal", "Diesa", "Eldeth", "Falkrunn", "Finellen", "Gunnloda", 
						"Gurdis", "Helja", "Hlin", "Kathra", "Kristryd", "Ilde", "Liftrasa", "Mardred", "Riswynn", "Sannl", "Torbera", "Torgga", 
						"Vistra",],
					".": "4",
				},
				"masculine": {
					"gender": ["masculine",],
					"firstname": ["Adrik", "Alberich", "Baern", "Barendd", "Brottor", "Bruenor", "Dain", "Darrak", "Delg", "Eberk", 
						"Einkil", "Fargrim", "Flint", "Gardain", "Harbek", "Kildrak", "Morgran", "Orsik", "Oskar", "Rangrim", "Rurik", 
						"Taklinn", "Thoradin", "Thorin", "Tordek", "Traubon", "Travok", "Ulfgar", "Veit", "Vondal"],
					".": "4",
				},
			},
			"sex": {
				".": "",
				"none": {
					".": "5",
					"sex": ["none",],
				},
				"all": {
					".": "5",
					"sex": ["all",],
				},
				"male": {
					".": "45",
					"sex": ["male",],
				},
				"female": {
					".": "45",
					"sex": ["female",],
				},
			},
			"age": {
				".": "",
				"venerable": {
					".": "1",
					"age": ["venerable",],
					"level": "9-15",
					"weight": "1.3-1.7",
					"height": "50-60",
					"years": "250-400",
					"hp": "6-15",
					"dex": "6-12",
					"int": "10-18",
					"chr": "10-18",
					"wis": "10-18",
					"str": "4-8",
					"con": "4-8",
				},
				"old": {
					".": "3",
					"weight": "0.9-1.8",
					"level": "5-10",
					"age": ["old",],
					"height": "45-60",
					"years": "175-250",
					"hp": "15-30",
					"dex": "7-15",
					"int": "8-16",
					"chr": "8-16",
					"wis": "8-16",
					"str": "7-15",
					"con": "7-15",
				},
				"middle": {
					".": "7",
					"weight": "1.1-2.0",
					"level": "7-10",
					"age": ["middle",],
					"height": "50-65",
					"years": "125-175",
					"hp": "12-21",
					"dex": "8-16",
					"int": "8-16",
					"chr": "8-16",
					"wis": "8-16",
					"str": "8-16",
					"con": "8-16",
				},
				"adult": {
					".": "10",
					"weight": "1.3-2.2",
					"level": "2-5",
					"age": ["adult",],
					"height": "55-70",
					"years": "40-125",
					"hp": "6-15",
					"dex": "8-16",
					"int": "8-16",
					"chr": "8-16",
					"wis": "8-16",
					"str": "8-16",
					"con": "8-16",
				},
				"youth": {
					".": "11",
					"weight": "1.3-2.2",
					"level": "1-2",
					"age": ["youth",],
					"height": "55-70",
					"years": "18-40",
					"hp": "3-8",
					"dex": "8-16",
					"int": "8-16",
					"chr": "8-16",
					"wis": "8-16",
					"str": "8-16",
					"con": "8-16",
				},
				"child": {
					".": "11",
					"weight": "1-1.3",
					"level": "1-1",
					"age": ["child",],
					"height": "37-54",
					"years": "6-18",
					"hp": "1-3",
					"dex": "3-9",
					"int": "2-8",
					"chr": "4-12",
					"wis": "1-5",
					"str": "1-5",
					"con": "1-5",
				},
				"baby": {
					".": "9",
					"weight": "0.4-1",
					"level": "1-1",
					"age": ["baby",],
					"height": "19-36",
					"years": "0-6",
					"hp": "1-1",
					"dex": "1-1",
					"int": "1-1",
					"chr": "1-1",
					"wis": "1-1",
					"str": "1-1",
					"con": "1-1",
				},
			},
		},
		"elf": {
			".": "1",
			"race": ["elf",],
			"skin": ["white","yellow","red","olive","brown","black",],
			"hair": ["white","blond","red","brown","black",],
			"eyes": ["gray","blue","green","yellow","hazel","brown",],
			"lastname": ["Amakiir (Gemflower)", "Amastacia (Starflower)", "Galanodel (Moonwhisper)", "Holimion (Diamonddew)", 
				"Ilphelkiir (Gemblossom)", "Liadon (Silverfrond)", "Meliamne (Oakenheel)", "Naïlo (Nightbreeze)", "Siannodel (Moonbrook)", 
				"Xiloscient (Goldpetal)"],
			"nickname": ["Ara", "Bryn", "Del", "Eryn", "Faen", "Innil", "Lael", "Mella", "Naill", "Naeris", "Phann", "Rael", "Rinn", "Sai", 
				"Syllin", "Thia", "Vall"],
			"alignments": {
				".": "",
				"lg": {".": "1", "alignment": ["lawful good",],},
				"ng": {".": "2", "alignment": ["neutral good",],},
				"cg": {".": "3", "alignment": ["chaotic good",],},
				"ln": {".": "2", "alignment": ["lawful neutral",],},
				"nn": {".": "2", "alignment": ["neutral neutral",],},
				"cn": {".": "2", "alignment": ["chaotic neutral",],},
				"le": {".": "3", "alignment": ["lawful evil",],},
				"ne": {".": "2", "alignment": ["neutral evil",],},
				"ce": {".": "1", "alignment": ["chaotic evil",],},
			},
			"gender": {
				".": "",
				"neutral": {
					"gender": ["neutral",],
					"firstname": ["Adran", "Aelar", "Aramil", "Arannis", "Aust", "Beiro", "Berrian", "Carric", "Enialis", "Erdan", 
						"Quillathe", "Sariel", "Shanairra", "Shava", "Silaqui", "Theirastra", "Thia", "Vadania", "Valanthe", "Xanaphia"],
					".": "2",
				},
				"variable": {
					"gender": ["variable",],
					"firstname": ["Adrie", "Althaea", "Anastrianna", "Andraste", "Antinua", "Bethrynna", "Birel", "Caelynn", "Drusilia", 
						"Peren", "Quarion", "Riardon", "Rolen", "Soveliss", "Thamior", "Tharivol", "Theren", "Varis"],
					".": "2",
				},
				"feminine": {
					"gender": ["feminine",],
					"firstname": ["Adrie", "Althaea", "Anastrianna", "Andraste", "Antinua", "Bethrynna", "Birel", "Caelynn", "Drusilia", 
						"Enna", "Felosial", "Ielenia", "Jelenneth", "Keyleth", "Leshanna", "Lia", "Meriele", "Mialee", "Naivara", "Quelenna", 
						"Quillathe", "Sariel", "Shanairra", "Shava", "Silaqui", "Theirastra", "Thia", "Vadania", "Valanthe", "Xanaphia"],
					".": "4",
				},
				"masculine": {
					"gender": ["masculine",],
					"firstname": ["Adran", "Aelar", "Aramil", "Arannis", "Aust", "Beiro", "Berrian", "Carric", "Enialis", "Erdan", 
						"Erevan", "Galinndan", "Hadarai", "Heian", "Himo", "Immeral", "Ivellios", "Laucian", "Mindartis", "Paelias", 
						"Peren", "Quarion", "Riardon", "Rolen", "Soveliss", "Thamior", "Tharivol", "Theren", "Varis"],
					".": "4",
				},
			},
			"sex": {
				".": "",
				"none": {
					".": "5",
					"sex": ["none",],
				},
				"all": {
					".": "5",
					"sex": ["all",],
				},
				"male": {
					".": "45",
					"sex": ["male",],
				},
				"female": {
					".": "45",
					"sex": ["female",],
				},
			},
			"age": {
				".": "",
				"venerable": {
					".": "1",
					"age": ["venerable",],
					"level": "9-15",
					"weight": "1.3-1.7",
					"height": "50-60",
					"years": "750-1250",
					"hp": "6-15",
					"dex": "6-12",
					"int": "10-18",
					"chr": "10-18",
					"wis": "10-18",
					"str": "4-8",
					"con": "4-8",
				},
				"old": {
					".": "3",
					"weight": "0.9-1.8",
					"level": "5-10",
					"age": ["old",],
					"height": "45-60",
					"years": "500-750",
					"hp": "15-30",
					"dex": "7-15",
					"int": "8-16",
					"chr": "8-16",
					"wis": "8-16",
					"str": "7-15",
					"con": "7-15",
				},
				"middle": {
					".": "7",
					"weight": "1.1-2.0",
					"level": "7-10",
					"age": ["middle",],
					"height": "50-65",
					"years": "250-500",
					"hp": "12-21",
					"dex": "8-16",
					"int": "8-16",
					"chr": "8-16",
					"wis": "8-16",
					"str": "8-16",
					"con": "8-16",
				},
				"adult": {
					".": "10",
					"weight": "1.3-2.2",
					"level": "2-5",
					"age": ["adult",],
					"height": "55-70",
					"years": "100-250",
					"hp": "6-15",
					"dex": "8-16",
					"int": "8-16",
					"chr": "8-16",
					"wis": "8-16",
					"str": "8-16",
					"con": "8-16",
				},
				"youth": {
					".": "11",
					"weight": "1.3-2.2",
					"level": "1-2",
					"age": ["youth",],
					"height": "55-70",
					"years": "30-100",
					"hp": "3-8",
					"dex": "8-16",
					"int": "8-16",
					"chr": "8-16",
					"wis": "8-16",
					"str": "8-16",
					"con": "8-16",
				},
				"child": {
					".": "11",
					"weight": "1-1.3",
					"level": "1-1",
					"age": ["child",],
					"height": "37-54",
					"years": "10-30",
					"hp": "1-3",
					"dex": "3-9",
					"int": "2-8",
					"chr": "4-12",
					"wis": "1-5",
					"str": "1-5",
					"con": "1-5",
				},
				"baby": {
					".": "9",
					"weight": "0.4-1",
					"level": "1-1",
					"age": ["baby",],
					"height": "19-36",
					"years": "0-10",
					"hp": "1-1",
					"dex": "1-1",
					"int": "1-1",
					"chr": "1-1",
					"wis": "1-1",
					"str": "1-1",
					"con": "1-1",
				},
			},
		},
		"gnome": {
			".": "1",
			"race": ["gnome",],
			"skin": ["white","yellow","red","olive","brown","black",],
			"hair": ["white","blond","red","brown","black",],
			"eyes": ["gray","blue","green","yellow","hazel","brown",],
			"speed": "25",
			"lastname": ["Beren", "Daergel", "Folkor", "Garrick", "Nackle", "Murnig", "Ningel", "Raulnor", "Scheppen", "Timbers", "Turen",],
			"nickname": ["Aleslosh", "Ashhearth", "Badger", "Cloak", "Doublelock", "Filchbatter", "Fnipper", "Ku", "Nim", "Oneshoe", "Pock", "Sparklegem", "Stumbleduck",],
			"alignments": {
				".": "",
				"lg": {".": "1", "alignment": ["lawful good",],},
				"ng": {".": "2", "alignment": ["neutral good",],},
				"cg": {".": "3", "alignment": ["chaotic good",],},
				"ln": {".": "2", "alignment": ["lawful neutral",],},
				"nn": {".": "2", "alignment": ["neutral neutral",],},
				"cn": {".": "2", "alignment": ["chaotic neutral",],},
				"le": {".": "3", "alignment": ["lawful evil",],},
				"ne": {".": "2", "alignment": ["neutral evil",],},
				"ce": {".": "1", "alignment": ["chaotic evil",],},
			},
			"gender": {
				".": "",
				"neutral": {
					".": "1",
					"gender": ["neutral",],
					"firstname": ["",],
				},
				"variable": {
					".": "1",
					"gender": ["variable",],
					"firstname": ["",],
				},
				"feminine": {
					".": "1",
					"gender": ["feminine",],
					"firstname": ["Bimpnottin", "Breena", "Caramip", "Carlin", "Donella", "Duvamil", "Ella", "Ellyjobell", "Ellywick", "Lilli", "Loopmottin", "Lorilla", "Mardnab", "Nissa", "Nyx", "Oda", "Orla", "Roywyn", "Shamil", "Tana", "Waywocket", "Zanna",],
				},
				"masculine": {
					".": "1",
					"gender": ["masculine",],
					"firstname": ["Alston", "Alvyn", "Boddynock", "Brocc", "Burgell", "Dimble", "Eldon", "Erky", "Fonkin", "Frug", "Gerbo", "Gimble", "Glim", "Jebeddo", "Kellen", "Namfoodle", "Orryn", "Roondar", "Seebo", "Sindri", "Warryn", "Wrenn", "Zook",],
				},
			},
			"sex": {
				".": "",
				"none": {
					".": "1",
					"sex": ["none",],
				},
				"all": {
					".": "1",
					"sex": ["all",],
				},
				"male": {
					".": "1",
					"sex": ["male",],
				},
				"female": {
					".": "1",
					"sex": ["female",],
				},
			},
			"age": {
				".": "",
				"venerable": {
					".": "1",
					"age": ["venerable",],
					"level": "11-15",
					"weight": "1.3-1.7",
					"height": "50-60",
					"years": "90-120",
					"hp": "6-15",
					"dex": "6-12",
					"int": "10-18",
					"chr": "10-18",
					"wis": "10-18",
					"str": "4-8",
					"con": "4-8",
				},
				"old": {
					".": "3",
					"weight": "0.9-1.8",
					"level": "9-12",
					"age": ["old",],
					"height": "45-60",
					"years": "60-90",
					"hp": "15-30",
					"dex": "6-15",
					"int": "8-16",
					"chr": "8-16",
					"wis": "8-16",
					"str": "7-11",
					"con": "6-15",
				},
				"middle": {
					".": "7",
					"weight": "1.1-2.0",
					"level": "7-10",
					"age": ["middle",],
					"height": "50-65",
					"years": "45-60",
					"hp": "12-21",
					"dex": "9-12",
					"int": "9-12",
					"chr": "9-12",
					"wis": "9-12",
					"str": "9-12",
					"con": "9-12",
				},
				"adult": {
					".": "10",
					"weight": "1.3-2.2",
					"level": "2-6",
					"age": ["adult",],
					"height": "55-70",
					"years": "20-45",
					"hp": "6-15",
					"dex": "9-12",
					"int": "9-12",
					"chr": "9-12",
					"wis": "9-12",
					"str": "9-12",
					"con": "9-12",
				},
				"youth": {
					".": "11",
					"weight": "1.3-2.2",
					"level": "1-2",
					"age": ["youth",],
					"height": "55-70",
					"years": "10-20",
					"hp": "3-8",
					"dex": "9-12",
					"int": "9-12",
					"chr": "9-12",
					"wis": "9-12",
					"str": "9-12",
					"con": "9-12",
				},
				"child": {
					".": "11",
					"weight": "1-1.3",
					"level": "1-1",
					"age": ["child",],
					"height": "37-54",
					"years": "3-10",
					"hp": "1-3",
					"dex": "6-9",
					"int": "6-9",
					"chr": "6-9",
					"wis": "6-9",
					"str": "6-9",
					"con": "6-9",
				},
				"baby": {
					".": "9",
					"age": ["baby",],
					"years": "0-3",
					"level": "1-1",
					"height": "19-36",
					"weight": "0.4-1",
					"hp": "1-1",
					"dex": "1-1",
					"int": "1-1",
					"chr": "1-1",
					"wis": "1-1",
					"str": "1-1",
					"con": "1-1",
				},
			},
		},
		"halfling": {
			".": "1",
			"race": ["halfling",],
			"skin": ["white","yellow","red","olive","brown","black",],
			"hair": ["white","blond","red","brown","black",],
			"eyes": ["gray","blue","green","yellow","hazel","brown",],
			"speed": "20",
			"lastname": ["Brushgather", "Goodbarrel", "Greenbottle", "High-hill", "Hilltopple", "Leagallow", "Tealeaf", "Thorngage", "Tosscobble", "Underbough",],
			"nickname": ["",],
			"alignments": {
				".": "",
				"lg": {".": "1", "alignment": ["lawful good",],},
				"ng": {".": "2", "alignment": ["neutral good",],},
				"cg": {".": "3", "alignment": ["chaotic good",],},
				"ln": {".": "2", "alignment": ["lawful neutral",],},
				"nn": {".": "2", "alignment": ["neutral neutral",],},
				"cn": {".": "2", "alignment": ["chaotic neutral",],},
				"le": {".": "3", "alignment": ["lawful evil",],},
				"ne": {".": "2", "alignment": ["neutral evil",],},
				"ce": {".": "1", "alignment": ["chaotic evil",],},
			},
			"gender": {
				".": "",
				"neutral": {
					".": "1",
					"gender": ["neutral",],
					"firstname": ["",],
				},
				"variable": {
					".": "1",
					"gender": ["variable",],
					"firstname": ["",],
				},
				"feminine": {
					".": "1",
					"gender": ["feminine",],
					"firstname": ["Andry", "Bree", "Callie", "Cora", "Euphemia", "Jillian", "Kithri", "Lavinia", "Lidda", "Merla", "Nedda", "Paela", "Portia", "Seraphina", "Shaena", "Trym", "Vani", "Verna",],
				},
				"masculine": {
					".": "1",
					"gender": ["masculine",],
					"firstname": ["Alton", "Ander", "Cade", "Corrin", "Eldon", "Errich", "Finnan", "Garret", "Lindal", "Lyle", "Merric", "Milo", "Osborn", "Perrin", "Reed", "Roscoe", "Wellby",],
				},
			},
			"sex": {
				".": "",
				"none": {
					".": "1",
					"sex": ["none",],
				},
				"all": {
					".": "1",
					"sex": ["all",],
				},
				"male": {
					".": "1",
					"sex": ["male",],
				},
				"female": {
					".": "1",
					"sex": ["female",],
				},
			},
			"age": {
				".": "",
				"venerable": {
					".": "1",
					"age": ["venerable",],
					"level": "11-15",
					"weight": "1.3-1.7",
					"height": "50-60",
					"years": "100-150",
					"hp": "6-15",
					"dex": "6-12",
					"int": "10-18",
					"chr": "10-18",
					"wis": "10-18",
					"str": "4-8",
					"con": "4-8",
				},
				"old": {
					".": "3",
					"weight": "0.9-1.8",
					"level": "9-12",
					"age": ["old",],
					"height": "45-60",
					"years": "75-100",
					"hp": "15-30",
					"dex": "6-15",
					"int": "8-16",
					"chr": "8-16",
					"wis": "8-16",
					"str": "7-11",
					"con": "6-15",
				},
				"middle": {
					".": "7",
					"weight": "1.1-2.0",
					"level": "7-10",
					"age": ["middle",],
					"height": "50-65",
					"years": "50-75",
					"hp": "12-21",
					"dex": "9-12",
					"int": "9-12",
					"chr": "9-12",
					"wis": "9-12",
					"str": "9-12",
					"con": "9-12",
				},
				"adult": {
					".": "10",
					"weight": "1.3-2.2",
					"level": "2-6",
					"age": ["adult",],
					"height": "55-70",
					"years": "20-50",
					"hp": "6-15",
					"dex": "9-12",
					"int": "9-12",
					"chr": "9-12",
					"wis": "9-12",
					"str": "9-12",
					"con": "9-12",
				},
				"youth": {
					".": "11",
					"weight": "1.3-2.2",
					"level": "1-2",
					"age": ["youth",],
					"height": "55-70",
					"years": "10-20",
					"hp": "3-8",
					"dex": "9-12",
					"int": "9-12",
					"chr": "9-12",
					"wis": "9-12",
					"str": "9-12",
					"con": "9-12",
				},
				"child": {
					".": "11",
					"weight": "1-1.3",
					"level": "1-1",
					"age": ["child",],
					"height": "37-54",
					"years": "3-10",
					"hp": "1-3",
					"dex": "6-9",
					"int": "6-9",
					"chr": "6-9",
					"wis": "6-9",
					"str": "6-9",
					"con": "6-9",
				},
				"baby": {
					".": "9",
					"age": ["baby",],
					"years": "0-3",
					"level": "1-1",
					"height": "19-36",
					"weight": "0.4-1",
					"hp": "1-1",
					"dex": "1-1",
					"int": "1-1",
					"chr": "1-1",
					"wis": "1-1",
					"str": "1-1",
					"con": "1-1",
				},
			},
		},
		"tiefling": {
			".": "1",
			"race": ["tiefling",],
			"skin": ["white","yellow","red","olive","brown","black",],
			"hair": ["white","blond","red","brown","black",],
			"eyes": ["gray","blue","green","yellow","hazel","brown",],
			"speed": "20",
			"lastname": ["",],
			"nickname": ["Art", "Carrion", "Chant", "Creed", "Despair", "Excellence", "Fear", "Glory", "Hope", "Ideal", "Music", "Nowhere", "Open", "Poetry", "Quest", "Random", "Reverence", "Sorrow", "Temerity", "Torment", "Weary",],
			"alignments": {
				".": "",
				"lg": {".": "1", "alignment": ["lawful good",],},
				"ng": {".": "2", "alignment": ["neutral good",],},
				"cg": {".": "3", "alignment": ["chaotic good",],},
				"ln": {".": "2", "alignment": ["lawful neutral",],},
				"nn": {".": "2", "alignment": ["neutral neutral",],},
				"cn": {".": "2", "alignment": ["chaotic neutral",],},
				"le": {".": "3", "alignment": ["lawful evil",],},
				"ne": {".": "2", "alignment": ["neutral evil",],},
				"ce": {".": "1", "alignment": ["chaotic evil",],},
			},
			"gender": {
				".": "",
				"neutral": {
					".": "1",
					"gender": ["neutral",],
					"firstname": ["Akta", "Anakis", "Bryseis", "Criella", "Damaia", "Ea", "Kallista", "Lerissa", "Makaria", "Nemeia", "Orianna", "Phelaia", "Rieta",
						"Akmenos", "Amnon", "Barakas", "Damakos", "Ekemon", "Iados", "Kairon", "Leucis", "Melech", "Mordai", "Morthos", "Pelaios", "Skamos", "Therai",],
				},
				"variable": {
					".": "1",
					"gender": ["variable",],
					"firstname": ["Akta", "Anakis", "Bryseis", "Criella", "Damaia", "Ea", "Kallista", "Lerissa", "Makaria", "Nemeia", "Orianna", "Phelaia", "Rieta",
						"Akmenos", "Amnon", "Barakas", "Damakos", "Ekemon", "Iados", "Kairon", "Leucis", "Melech", "Mordai", "Morthos", "Pelaios", "Skamos", "Therai",],
				},
				"feminine": {
					".": "1",
					"gender": ["feminine",],
					"firstname": ["Akta", "Anakis", "Bryseis", "Criella", "Damaia", "Ea", "Kallista", "Lerissa", "Makaria", "Nemeia", "Orianna", "Phelaia", "Rieta",],
				},
				"masculine": {
					".": "1",
					"gender": ["masculine",],
					"firstname": ["Akmenos", "Amnon", "Barakas", "Damakos", "Ekemon", "Iados", "Kairon", "Leucis", "Melech", "Mordai", "Morthos", "Pelaios", "Skamos", "Therai",],
				},
			},
			"sex": {
				".": "",
				"none": {
					".": "1",
					"sex": ["none",],
				},
				"all": {
					".": "1",
					"sex": ["all",],
				},
				"male": {
					".": "1",
					"sex": ["male",],
				},
				"female": {
					".": "1",
					"sex": ["female",],
				},
			},
			"age": {
				".": "",
				"venerable": {
					".": "1",
					"age": ["venerable",],
					"level": "11-15",
					"weight": "1.3-1.7",
					"height": "50-60",
					"years": "90-120",
					"hp": "6-15",
					"dex": "6-12",
					"int": "10-18",
					"chr": "10-18",
					"wis": "10-18",
					"str": "4-8",
					"con": "4-8",
				},
				"old": {
					".": "3",
					"weight": "0.9-1.8",
					"level": "9-12",
					"age": ["old",],
					"height": "45-60",
					"years": "60-90",
					"hp": "15-30",
					"dex": "6-15",
					"int": "8-16",
					"chr": "8-16",
					"wis": "8-16",
					"str": "7-11",
					"con": "6-15",
				},
				"middle": {
					".": "7",
					"weight": "1.1-2.0",
					"level": "7-10",
					"age": ["middle",],
					"height": "50-65",
					"years": "45-60",
					"hp": "12-21",
					"dex": "9-12",
					"int": "9-12",
					"chr": "9-12",
					"wis": "9-12",
					"str": "9-12",
					"con": "9-12",
				},
				"adult": {
					".": "10",
					"weight": "1.3-2.2",
					"level": "2-6",
					"age": ["adult",],
					"height": "55-70",
					"years": "20-45",
					"hp": "6-15",
					"dex": "9-12",
					"int": "9-12",
					"chr": "9-12",
					"wis": "9-12",
					"str": "9-12",
					"con": "9-12",
				},
				"youth": {
					".": "11",
					"weight": "1.3-2.2",
					"level": "1-2",
					"age": ["youth",],
					"height": "55-70",
					"years": "10-20",
					"hp": "3-8",
					"dex": "9-12",
					"int": "9-12",
					"chr": "9-12",
					"wis": "9-12",
					"str": "9-12",
					"con": "9-12",
				},
				"child": {
					".": "11",
					"weight": "1-1.3",
					"level": "1-1",
					"age": ["child",],
					"height": "37-54",
					"years": "3-10",
					"hp": "1-3",
					"dex": "6-9",
					"int": "6-9",
					"chr": "6-9",
					"wis": "6-9",
					"str": "6-9",
					"con": "6-9",
				},
				"baby": {
					".": "9",
					"age": ["baby",],
					"years": "0-3",
					"level": "1-1",
					"height": "19-36",
					"weight": "0.4-1",
					"hp": "1-1",
					"dex": "1-1",
					"int": "1-1",
					"chr": "1-1",
					"wis": "1-1",
					"str": "1-1",
					"con": "1-1",
				},
			},
		},
	},
	"background": {
		".": "",
		"acolyte": {
			".": "1",
			"background": ["acolyte"],
			"desc": ["Acolytes are shaped by their experience in temples or other religious communities. Their study of the history and tenets of their faith and their relationships to temples, shrines, or hierarchies affect their mannerisms and ideals. Their flaws might be some hidden hypocrisy or heretical idea, or an ideal or bond taken to an extreme.",],
			"specialty": ["",],
			"trait": [
				"I idolize a particular hero of my faith, and constantly refer to that person's deeds and example.",
				"I can find common ground between the fiercest enemies, empathizing with them and always working toward peace.",
				"I see omens in every event and action. The gods try to speak to us, we just need to listen",
				"Nothing can shake my optimistic attitude.",
				"I quote (or misquote) sacred texts and proverbs in almost every situation.",
				"I am tolerant (or intolerant) of other faiths and respect (or condemn) the worship of other gods.",
				"I've enjoyed fine food, drink, and high society among my temple's elite. Rough living grates on me.",
				"I've spent so long in the temple that I have little practical experience dealing with people in the outside world.",
			],
			"ideal": [
				"Tradition. The ancient traditions of worship and sacrifice must be preserved and upheld. (Lawful)",
				"Charity. I always try to help those in need, no matter what the personal cost. (Good)",
				"Change. We must help bring about the changes the gods are constantly working in the world. (Chaotic)",
				"Power. I hope to one day rise to the top of my faith's religious hierarchy. (Lawful)",
				"Faith. I trust that my deity will guide my actions, I have faith that if I work hard, things will go well. (Lawful)",
				"Aspiration. I seek to prove myself worthy of my god's favor by matching my actions against his or her teachings. (Any)",
			],
			"bond": [
				"I would die to recover an ancient relic of my faith that was lost long ago.",
				"I will someday get revenge on the corrupt temple hierarchy who branded me a heretic.",
				"I owe my life to the priest who took me in when my parents died.",
				"Everything I do is for the common people.",
				"I will do anything to protect the temple where I served.",
				"I seek to preserve a sacred text that my enemies consider heretical and seek to destroy.",
			],
			"flaw": [
				"I judge others harshly, and myself even more severely.",
				"I put too much trust in those who wield power within my temple's hierarchy.",
				"My piety sometimes leads me to blindly trust those that profess faith in my god.",
				"I am inflexible in my thinking.",
				"I am suspicious of strangers and expect the worst of them.",
				"Once I pick a goal, I become obsessed with it to the detriment of everything else in my life.",
			],
		},
		"charlatan": {
			".": "1",
			"background": ["charlatan"],
			"desc": ["Charlatans are colorful characters who conceal their true selves behind the masks they construct. They reflect what people want to see, what they want to believe, and how they see the world. But their true selves are sometimes plagued by an uneasy conscience, an old enemy, or deep-seated trust issues.",],
			"specialty": [
				"I cheat at games of chance.",
				"I shave coins or forge documents.",
				"I insinuate myself into people's lives to prey on their weakness and secure their fortunes.",
				"I put on new identities like clothes.",
				"I run sleight-of-hand cons on street corners.",
				"I convince people that worthless junk is worth their hard-earned money.",
			],
			"trait": [
				"I fall in and out of love easily, and am always pursuing someone.",
				"I have a joke for every occasion, especially occasions where humor is inappropriate.",
				"Flattery is my preferred trick for getting what I want.",
				"I'm a born gambler who can't resist taking a risk for a potential payoff.",
				"I lie about almost everything, even when there's no good reason to.",
				"Sarcasm and insults are my weapons of choice.",
				"I keep multiple holy symbols on me and invoke whatever deity might come in useful at any given moment.",
				"I pocket anything I see that might have some value.",
			],
			"ideal": [
				"Independence. I am a free spirit — no one tells me what to do. (Chaotic)",
				"Fairness. I never target people who can't afford to lose a few coins. (Lawful)",
				"Charity. I distribute the money I acquire to the people who really need it. (Good)",
				"Creativity. I never run the same con twice. (Chaotic)",
				"Friendship. Material goods come and go. Bonds of friendship last forever. (Good)",
				"Aspiration. I'm determined to make something of myself. (Any)",
			],
			"bond": [
				"I fleeced the wrong person and must work to ensure that this individual never crosses paths with me or those I care about.",
				"I owe everything to my mentor — a horrible person who's probably rotting in jail somewhere.",
				"Somewhere out there, I have a child who doesn't know me. I'm making the world better for him or her.",
				"I come from a noble family, and one day I'll reclaim my lands and title from those who stole them from me.",
				"A powerful person killed someone I love. Some day soon, I'll have my revenge.",
				"I swindled and ruined a person who didn't deserve it. I seek to atone for my misdeeds but might never be able to forgive myself.",
			],
			"flaw": [
				"I can't resist a pretty face.",
				"I'm always in debt. I spend my ill-gotten gains on decadent luxuries faster than I bring them in.",
				"I'm convinced that no one could ever fool me the way I fool others.",
				"I'm too greedy for my own good. I can't resist taking a risk if there's money involved.",
				"I can't resist swindling people who are more powerful than me.",
				"I hate to admit it and will hate myself for it, but I'll run and preserve my own hide if the going gets tough.",
			],
		},
		"criminal": {
			".": "1",
			"background": ["criminal"],
			"desc": ["Criminals might seem like villains on the surface, and many of them are villainous to the core. But some have an abundance of endearing, if not redeeming, characteristics. There might be honor among thieves, but criminals rarely show any respect for law or authority.",],
			"specialty": [
				"Blackmailer",
				"Burglar",
				"Enforcer",
				"Fence",
				"Highway robber",
				"Hired killer",
				"Pickpocket",
				"Smuggler",
			],
			"trait": [
				"I always have a plan for what to do when things go wrong.",
				"I am always calm, no matter what the situation. I never raise my voice or let my emotions control me.",
				"The first things to do in a new place is note the locations of everything valuable — or where such things could be hidden.",
				"I would rather make a new friend than a new enemy.",
				"I am incredibly slow to trust. Those who seem the fairest often have the most to hide.",
				"I don't pay attention to the risks in a situation. Never tell me the odds.",
				"The best way to get me to do something is to tell me I can't do it.",
				"I blow up at the slightest insult.",
			],
			"ideal": [
				"Honor. I don't steal from others in the trade. (Lawful)",
				"Freedom. Chains are meant to be broken, as are those who would forge them. (Chaotic)",
				"Charity. I steal from the wealthy so that I can help people in need. (Good)",
				"Greed. I will do whatever it takes to become wealthy. (Evil)",
				"People. I'm loyal to my friends, not to any ideals, and everyone else can take a trip down the Styx for all I care. (Neutral)",
				"Redemption. There's a spark of good in everyone. (Good)",
			],
			"bond": [
				"I'm trying to pay off an old debt I owe to a generous benefactor.",
				"My ill-gotten gains go to support my family.",
				"Something important was taken from me, and I aim to steal it back.",
				"I will become the greatest thief that ever lived.",
				"I'm guilty of a terrible crime. I hope I can redeem myself for it.",
				"Someone I loved died because of a mistake I made. That will never happen again.",
			],
			"flaw": [
				"When I see something valuable, I can't think about anything but how to steal it.",
				"When faced with a choice between money and my friends, I usually choose the money.",
				"If there's a plan, I'll forget it. If I don't forget it, I'll ignore it.",
				"I have a \"tell\" that reveals when I'm lying.",
				"I turn tail and run when things look bad.",
				"An innocent person is in prison for a crime that I committed. I'm okay with that.",
			],
		},
		"entertainer": {
			".": "1",
			"background": ["entertainer"],
			"desc": ["Successful entertainers have to be able to capture and hold an audience's attention, so they tend to have flamboyant or forceful personalities. They're inclined toward the romantic and often cling to high-minded ideals about the practice of art and the appreciation of beauty.",],
			"specialty": [
				"Actor",
				"Dancer",
				"Fire-eater",
				"Jester",
				"Juggler",
				"Instrumentalist",
				"Poet",
				"Singer",
				"Storyteller",
				"Tumbler",
			],
			"trait": [
				"I know a story relevant to almost every situation.",
				"Whenever I come to a new place, I collect local rumors and spread gossip.",
				"I'm a hopeless romantic, always searching for that special someone.",
				"Nobody stays angry at me or around me for long, since I can defuse any amount of tension.",
				"I love a good insult, even one directed at me.",
				"I get bitter if I'm not the center of attention.",
				"I'll settle for nothing less than perfection.",
				"I change my mood or my mind as quickly as I change key in a song.",
			],
			"ideal": [
				"Beauty. When I perform, I make the world better than it was. (Good)",
				"Tradition. The stories, legends, and songs of the past must never be forgotten, for they teach us who we are. (Lawful)",
				"Creativity. The world is in need of new ideas and bold action. (Chaotic)",
				"Greed. I'm only in it for the money and fame. (Evil)",
				"People. I like seeing the smiles on people's faces when I perform. That's all that matters. (Neutral)",
				"Honesty. Art should reflect the soul; it should come from within and reveal who we really are. (Any)",
			],
			"bond": [
				"My instrument is my most treasured possession, and it reminds me of someone I love.",
				"Someone stole my precious instrument, and someday I'll get it back.",
				"I want to be famous, whatever it takes.",
				"I idolize a hero of the old tales and measure my deeds against that person's.",
				"I will do anything to prove myself superior to my hated rival.",
				"I would do anything for the other members of my old troupe.",
			],
			"flaw": [
				"I'll do anything to win fame and renown.",
				"I'm a sucker for a pretty face.",
				"A scandal prevents me from ever going home again. That kind of trouble seems to follow me around.",
				"I once satirized a noble who still wants my head. It was a mistake that I will likely repeat.",
				"I have trouble keeping my true feelings hidden. My sharp tongue lands me in trouble.",
				"Despite my best efforts, I am unreliable to my friends.",
			],
		},
		"hero": {
			".": "1",
			"background": ["hero"],
			"desc": ["A folk hero is one of the common people, for better or for worse. Most folk heroes look on their humble origins as a virtue, not a shortcoming, and their home communities remain very important to them.",],
			"specialty": [
				"I stood up to a tyrant's agents.",
				"I saved people during a natural disaster.",
				"I stood alone against a terrible monster.",
				"I stole from a corrupt merchant to help the poor.",
				"I led a militia to fight off an invading army.",
				"I broke into a tyrant's castle and stole weapons to arm the people.",
				"I trained the peasantry to use farm implements as weapons against a tyrant's soldiers.",
				"A lord rescinded an unpopular decree after I led a symbolic act of protect against it.",
				"A celestial, fey, or similar creature gave me a blessing or revealed my secret origin.",
				"Recruited into a lord's army, I rose to leadership and was commended for my heroism.",
			],
			"trait": [
				"I judge people by their actions, not their words.",
				"If someone is in trouble, I'm always ready to lend help.",
				"When I set my mind to something, I follow through no matter what gets in my way.",
				"I have a strong sense of fair play and always try to find the most equitable solution to arguments.",
				"I'm confident in my own abilities and do what I can to instill confidence in others.",
				"Thinking is for other people. I prefer action.",
				"I misuse long words in an attempt to sound smarter.",
				"I get bored easily. When am I going to get on with my destiny?",
			],
			"ideal": [
				"Respect. People deserve to be treated with dignity and respect. (Good)",
				"Fairness. No one should get preferential treatment before the law, and no one is above the law. (Lawful)",
				"Freedom. Tyrants must not be allowed to oppress the people. (Chaotic)",
				"Might. If I become strong, I can take what I want — what I deserve. (Evil)",
				"Sincerity. There's no good in pretending to be something I'm not. (Neutral)",
				"Destiny. Nothing and no one can steer me away from my higher calling. (Any)",
			],
			"bond": [
				"I have a family, but I have no idea where they are. One day, I hope to see them again.",
				"I worked the land, I love the land, and I will protect the land.",
				"A proud noble once gave me a horrible beating, and I will take my revenge on any bully I encounter.",
				"My tools are symbols of my past life, and I carry them so that I will never forget my roots.",
				"I protect those who cannot protect themselves.",
				"I wish my childhood sweetheart had come with me to pursue my destiny.",
			],
			"flaw": [
				"The tyrant who rules my land will stop at nothing to see me killed.",
				"I'm convinced of the significance of my destiny, and blind to my shortcomings and the risk of failure.",
				"The people who knew me when I was young know my shameful secret, so I can never go home again.",
				"I have a weakness for the vices of the city, especially hard drink.",
				"Secretly, I believe that things would be better if I were a tyrant lording over the land.",
				"I have trouble trusting in my allies.",
			],
		},
		"artisan": {
			".": "1",
			"background": ["artisan"],
			"desc": ["Guild artisans are among the most ordinary people in the world — until they set down their tools and take up an adventuring career. They understand the value of hard work and the importance of community, but they're vulnerable to sins of greed and covetousness.",],
			"specialty": [
				"Alchemists and apothecaries",
				"Armorers, locksmiths, and finesmiths",
				"Brewers, distillers, and vintners",
				"Calligraphers, scribes, and scriveners",
				"Carpenters, roofers, and plasterers",
				"Cartographers, surveyors, and chart-makers",
				"Cobblers and shoemakers",
				"Cooks and bakers",
				"Glassblowers and glaziers",
				"Jewelers and gemcutters",
				"Leatherworkers, skinners, and tanners",
				"Masons and stonecutters",
				"Painters, limners, and sign-makers",
				"Potters and tile-makers",
				"Shipwrights and sailmakers",
				"Smiths and metal-forgers",
				"Tinkers, pewterers, and casters",
				"Wagon-makers and wheelwrights",
				"Weavers and dyers",
				"Woodcarvers, coopers, and bowyers",
			],
			"trait": [
				"I believe that anything worth doing is worth doing right. I can't help it — I'm a perfectionist.",
				"I'm a snob who looks down on those who can't appreciate fine art.",
				"I always want to know how things work and what makes people tick.",
				"I'm full of witty aphorisms and have a proverb for every occasion.",
				"I'm rude to people who lack my commitment to hard work and fair play.",
				"I like to talk at length about my profession.",
				"I don't part with my money easily and will haggle tirelessly to get the best deal possible.",
				"I'm well known for my work, and I want to make sure everyone appreciates it. I'm always taken aback when people haven't heard of me.",
			],
			"ideal": [
				"Community. It is the duty of all civilized people to strengthen the bonds of community and the security of civilization. (Lawful)",
				"Generosity. My talents were given to me so that I could use them to benefit the world. (Good)",
				"Freedom. Everyone should be free to pursue his or her own livelihood. (Chaotic)",
				"Greed. I'm only in it for the money. (Evil)",
				"People. I'm committed to the people I care about, not to ideals. (Neutral)",
				"Aspiration. I work hard to be the best there is at my craft.",
			],
			"bond": [
				"The workshop where I learned my trade is the most important place in the world to me.",
				"I created a great work for someone, and then found them unworthy to receive it. I'm still looking for someone worthy.",
				"I owe my guild a great debt for forging me into the person I am today.",
				"I pursue wealth to secure someone's love.",
				"One day I will return to my guild and prove that I am the greatest artisan of them all.",
				"I will get revenge on the evil forces that destroyed my place of business and ruined my livelihood.",
			],
			"flaw": [
				"I'll do anything to get my hands on something rare or priceless.",
				"I'm quick to assume that someone is trying to cheat me.",
				"No one must ever learn that I once stole money from guild coffers.",
				"I'm never satisfied with what I have — I always want more.",
				"I would kill to acquire a noble title.",
				"I'm horribly jealous of anyone who can outshine my handiwork. Everywhere I go, I'm surrounded by rivals.",
			],
		},
		"hermit": {
			".": "1",
			"background": ["hermit"],
			"desc": ["ome hermits are well suited to a life of seclusion, whereas others chafe against it and long for company. Whether they em brace solitude or long to escape it, the solitary life shapes their attitudes and ideals. A few are driven slightly mad by their years apart from society.",],
			"specialty": [
				"I was searching for spiritual enlightenment.",
				"I was partaking of communal living in accordance with the dictates of a religious order.",
				"I was exiled for a crime I didn't commit.",
				"I retreated from society after a life-altering event.",
				"I needed a quiet place to work on my art, literature, music, or manifesto.",
				"I needed to commune with nature, far from civilization.",
				"I was the caretaker of an ancient ruin or relic.",
				"I was a pilgrim in search of a person, place, or relic of spiritual significance.",
			],
			"trait": [
				"I've been isolated for so long that I rarely speak, preferring gestures and the occasional grunt.",
				"I am utterly serene, even in the face of disaster.",
				"The leader of my community had something wise to say on every topic, and I am eager to share that wisdom.",
				"I feel tremendous empathy for all who suffer.",
				"I'm oblivious to etiquette and social expectations.",
				"I connect everything that happens to me to a grand, cosmic plan.",
				"I often get lost in my own thoughts and contemplation, becoming oblivious to my surroundings.",
				"I am working on a grand philosophical theory and love sharing my ideas.",
			],
			"ideal": [
				"Greater Good. My gifts are meant to be shared with all, not used for my own benefit. (Good)",
				"Logic. Emotions must not cloud our sense of what is right and true, or our logical thinking. (Lawful)",
				"Free Thinking. Inquiry and curiosity are the pillars of progress. (Chaotic)",
				"Power. Solitude and contemplation are paths toward mystical or magical power. (Evil)",
				"Live and Let Live. Meddling in the affairs of others only causes trouble. (Neutral)",
				"Self-Knowledge. If you know yourself, there's nothing left to know. (Any)",
			],
			"bond": [
				"Nothing is more important than the other members of my hermitage, order, or association.",
				"I entered seclusion to hide from the ones who might still be hunting me. I must someday confront them.",
				"I'm still seeking the enlightenment I pursued in my seclusion, and it still eludes me.",
				"I entered seclusion because I loved someone I could not have.",
				"Should my discovery come to light, it could bring ruin to the world.",
				"My isolation gave me great insight into a great evil that only I can destroy.",
			],
			"flaw": [
				"Now that I've returned to the world, I enjoy its delights a little too much.",
				"I harbor dark, bloodthirsty thoughts that my isolation and meditation failed to quell.",
				"I am dogmatic in my thoughts and philosophy.",
				"I let my need to win arguments overshadow friendships and harmony.",
				"I'd risk too much to uncover a lost bit of knowledge.",
				"I like keeping secrets and won't share them with anyone.",
			],
		},
		"noble": {
			".": "1",
			"background": ["noble"],
			"desc": ["Nobles are born and raised to a very different lifestyle than most people ever experience, and their personalities reflect that upbringing. A noble title comes with a plethora of bonds — responsibilities to family, to other nobles (including the sovereign), to the people entrusted to the family's care, or even to the title itself. But this responsibility is often a good way to undermine a noble.",],
			"specialty": ["",],
			"trait": [
				"My eloquent flattery makes everyone I talk to feel like the most wonderful and important person in the world.",
				"The common folk love me for my kindness and generosity.",
				"No one could doubt by looking at my regal bearing that I am a cut above the unwashed masses.",
				"I take great pains to always look my best and follow the latest fashions.",
				"I don't like to get my hands dirty, and I won't be caught dead in unsuitable accommodations.",
				"Despite my noble birth, I do not place myself above other folk. We all have the same blood.",
				"My favor, once lost, is lost forever.",
				"If you do me an injury, I will crush you, ruin your name, and salt your fields.",
			],
			"ideal": [
				"Respect. Respect is due to me because of my position, but all people regardless of station deserve to be treated with dignity. (Good)",
				"Responsibility. It is my duty to respect the authority of those above me, just as those below me must respect mine. (Lawful)",
				"Independence. I must prove that I can handle myself without the coddling of my family. (Chaotic)",
				"Power. If I can attain more power, no one will tell me what to do. (Evil)",
				"Family. Blood runs thicker than water. (Any)",
				"Noble Obligation. It is my duty to protect and care for the people beneath me. (Good)",
			],
			"bond": [
				"I will face any challenge to win the approval of my family.",
				"My house's alliance with another noble family must be sustained at all costs.",
				"Nothing is more important than the other members of my family.",
				"I am in love with the heir of a family that my family despises.",
				"My loyalty to my sovereign is unwavering.",
				"The common folk must see me as a hero of the people.",
			],
			"flaw": [
				"I secretly believe that everyone is beneath me.",
				"I hide a truly scandalous secret that could ruin my family forever.",
				"I too often hear veiled insults and threats in every word addressed to me, and I'm quick to anger.",
				"I have an insatiable desire for carnal pleasures.",
				"In fact, the world does revolve around me.",
				"By my words and actions, I often bring shame to my family.",
			],
		},
		"outlander": {
			".": "1",
			"background": ["outlander"],
			"desc": ["Often considered rude and uncouth among civilized folk, outlanders have little respect for the niceties of life in the cities. The ties of tribe, clan, family, and the natural world of which they are a part are the most important bonds to most outlanders.",],
			"specialty": [
				"Forester",
				"Trapper",
				"Homesteader",
				"Guide",
				"Exile or outcast",
				"Bounty hunter",
				"Pilgrim",
				"Tribal nomad",
				"Hunter-gatherer",
				"Tribal marauder",
			],
			"trait": [
				"I'm driven by a wanderlust that led me away from home.",
				"I watch over my friends as if they were a litter of newborn pups.",
				"I once ran twenty-five miles without stopping to warn to my clan of an approaching orc horde. I'd do it again if I had to.",
				"I have a lesson for every situation, drawn from observing nature.",
				"I place no stock in wealthy or well-mannered folk. Money and manners won't save you from a hungry owlbear.",
				"I'm always picking things up, absently fiddling with them, and sometimes accidentally breaking them.",
				"I feel far more comfortable around animals than people.",
				"I was, in fact, raised by wolves.",
			],
			"ideal": [
				"Change. Life is like the seasons, in constant change, and we must change with it. (Chaotic)",
				"Greater Good. It is each person's responsibility to make the most happiness for the whole tribe. (Good)",
				"Honor. If I dishonor myself, I dishonor my whole clan. (Lawful)",
				"Might. The strongest are meant to rule. (Evil)",
				"Nature. The natural world is more important than all the constructs of civilization. (Neutral)",
				"Glory. I must earn glory in battle, for myself and my clan. (Any)",
			],
			"bond": [
				"My family, clan, or tribe is the most important thing in my life, even when they are far from me.",
				"An injury to the unspoiled wilderness of my home is an injury to me.",
				"I will bring terrible wrath down on the evildoers who destroyed my homeland.",
				"I am the last of my tribe, and it is up to me to ensure their names enter legend.",
				"I suffer awful visions of a coming disaster and will do anything to prevent it.",
				"It is my duty to provide children to sustain my tribe.",
			],
			"flaw": [
				"I am too enamored of ale, wine, and other intoxicants.",
				"There's no room for caution in a life lived to the fullest.",
				"I remember every insult I've received and nurse a silent resentment toward anyone who's ever wronged me.",
				"I am slow to trust members of other races, tribes, and societies.",
				"Violence is my answer to almost any challenge.",
				"Don't expect me to save those who can't save themselves. It is nature's way that the strong thrive and the weak perish.",
			],
		},
		"sage": {
			".": "1",
			"background": ["sage"],
			"desc": ["Sages are defined by their extensive studies, and their characteristics reflect this life of study. Devoted to scholarly pursuits, a sage values knowledge highly — sometimes in its own right, sometimes as a means toward other ideals.",],
			"specialty": [
				"Alchemist",
				"Astronomer",
				"Discredited academic",
				"Librarian",
				"Professor",
				"Researcher",
				"Wizard's apprentice",
				"Scribe",
			],
			"trait": [
				"I use polysyllabic words that convey the impression of great erudition.",
				"I've read every book in the world's greatest libraries — or I like to boast that I have.",
				"I'm used to helping out those who aren't as smart as I am, and I patiently explain anything and everything to others.",
				"There's nothing I like more than a good mystery.",
				"I'm willing to listen to every side of an argument before I make my own judgment.",
				"I … speak … slowly … when talking … to idiots, … which … almost … everyone … is … compared … to me.",
				"I am horribly, horribly awkward in social situations.",
				"I'm convinced that people are always trying to steal my secrets.",
			],
			"ideal": [
				"Knowledge. The path to power and self-improvement is through knowledge. (Neutral)",
				"Beauty. What is beautiful points us beyond itself toward what is true. (Good)",
				"Logic. Emotions must not cloud our logical thinking. (Lawful)",
				"No Limits. Nothing should fetter the infinite possibility inherent in all existence. (Chaotic)",
				"Power. Knowledge is the path to power and domination. (Evil)",
				"Self-Improvement. The goal of a life of study is the betterment of oneself. (Any)",
			],
			"bond": [
				"It is my duty to protect my students.",
				"I have an ancient text that holds terrible secrets that must not fall into the wrong hands.",
				"I work to preserve a library, university, scriptorium, or monastery.",
				"My life's work is a series of tomes related to a specific field of lore.",
				"I've been searching my whole life for the answer to a certain question.",
				"I sold my soul for knowledge. I hope to do great deeds and win it back.",
			],
			"flaw": [
				"I am easily distracted by the promise of information.",
				"Most people scream and run when they see a demon. I stop and take notes on its anatomy.",
				"Unlocking an ancient mystery is worth the price of a civilization.",
				"I overlook obvious solutions in favor of complicated ones.",
				"I speak without really thinking through my words, invariably insulting others.",
				"I can't keep a secret to save my life, or anyone else's.",
			],
		},
		"sailor": {
			".": "1",
			"background": ["sailor"],
			"desc": ["Sailors can be a rough lot, but the responsibilities of life on a ship make them generally reliable as well. Life aboard a ship shapes their outlook and forms their most important attachments.",],
			"specialty": ["",],
			"trait": [
				"My friends know they can rely on me, no matter what.",
				"I work hard so that I can play hard when the work is done.",
				"I enjoy sailing into new ports and making new friends over a flagon of ale.",
				"I stretch the truth for the sake of a good story.",
				"To me, a tavern brawl is a nice way to get to know a new city.",
				"I never pass up a friendly wager.",
				"My language is as foul as an otyugh nest.",
				"I like a job well done, especially if I can convince someone else to do it.",
			],
			"ideal": [
				"Respect. The thing that keeps a ship together is mutual respect between captain and crew. (Good)",
				"Fairness. We all do the work, so we all share in the rewards. (Lawful)",
				"Freedom. The sea is freedom — the freedom to go anywhere and do anything. (Chaotic)",
				"Mastery. I'm a predator, and the other ships on the sea are my prey. (Evil)",
				"People. I'm committed to my crewmates, not to ideals. (Neutral)",
				"Aspiration. Someday I'll own my own ship and chart my own destiny. (Any)",
			],
			"bond": [
				"I'm loyal to my captain first, everything else second.",
				"The ship is most important — crewmates and captains come and go.",
				"I'll always remember my first ship.",
				"In a harbor town, I have a paramour whose eyes nearly stole me from the sea.",
				"I was cheated out of my fair share of the profits, and I want to get my due.",
				"Ruthless pirates murdered my captain and crewmates, plundered our ship, and left me to die. Vengeance will be mine.",
			],
			"flaw": [
				"I follow orders, even if I think they're wrong.",
				"I'll say anything to avoid having to do extra work.",
				"Once someone questions my courage, I never back down no matter how dangerous the situation.",
				"Once I start drinking, it's hard for me to stop.",
				"I can't help but pocket loose coins and other trinkets I come across.",
				"My pride will probably lead to my destruction.",
			],
		},
		"soldier": {
			".": "1",
			"background": ["soldier"],
			"desc": ["The horrors of war combined with the rigid discipline of military service leave their mark on all soldiers, shaping their ideals, creating strong bonds, and often leaving them scarred and vulnerable to fear, shame, and hatred.",],
			"specialty": [
				"Officer",
				"Scout",
				"Infantry",
				"Cavalry",
				"Healer",
				"Quartermaster",
				"Standard bearer",
				"Support staff (cook, blacksmith, or the like)",
			],
			"trait": [
				"I'm always polite and respectful.",
				"I'm haunted by memories of war. I can't get the images of violence out of my mind.",
				"I've lost too many friends, and I'm slow to make new ones.",
				"I'm full of inspiring and cautionary tales from my military experience relevant to almost every combat situation.",
				"I can stare down a hell hound without flinching.",
				"I enjoy being strong and like breaking things.",
				"I have a crude sense of humor.",
				"I face problems head-on. A simple, direct solution is the best path to success.",
			],
			"ideal": [
				"Greater Good. Our lot is to lay down our lives in defense of others. (Good)",
				"Responsibility. I do what I must and obey just authority. (Lawful)",
				"Independence. When people follow orders blindly, they embrace a kind of tyranny. (Chaotic)",
				"Might. In life as in war, the stronger force wins. (Evil)",
				"Live and Let Live. Ideals aren't worth killing over or going to war for. (Neutral)",
				"Nation. My city, nation, or people are all that matter. (Any)",
			],
			"bond": [
				"I would still lay down my life for the people I served with.",
				"Someone saved my life on the battlefield. To this day, I will never leave a friend behind.",
				"My honor is my life.",
				"I'll never forget the crushing defeat my company suffered or the enemies who dealt it.",
				"Those who fight beside me are those worth dying for.",
				"I fight for those who cannot fight for themselves.",
			],
			"flaw": [
				"The monstrous enemy we faced in battle still leaves me quivering with fear.",
				"I have little respect for anyone who is not a proven warrior.",
				"I made a terrible mistake in battle cost many lives — and I would do anything to keep that mistake secret.",
				"My hatred of my enemies is blind and unreasoning.",
				"I obey the law, even if the law causes misery.",
				"I'd rather eat my armor than admit when I'm wrong.",
			],
		},
		"urchin": {
			".": "1",
			"background": ["urchin"],
			"desc": ["Urchins are shaped by lives of desperate poverty, for good and for ill. They tend to be driven either by a commitment to the people with whom they shared life on the street or by a burning desire to find a better life — and maybe get some payback on all the rich people who treated them badly.",],
			"trait": [
				"I hide scraps of food and trinkets away in my pockets.",
				"I ask a lot of questions.",
				"I like to squeeze into small places where no one else can get to me.",
				"I sleep with my back to a wall or tree, with everything I own wrapped in a bundle in my arms.",
				"I eat like a pig and have bad manners.",
				"I think anyone who's nice to me is hiding evil intent.",
				"I don't like to bathe.",
				"I bluntly say what other people are hinting at or hiding.",
			],
			"ideal": [
				"Respect. All people, rich or poor, deserve respect. (Good)",
				"Community. We have to take care of each other, because no one else is going to do it. (Lawful)",
				"Change. The low are lifted up, and the high and mighty are brought down. Change is the nature of things. (Chaotic)",
				"Retribution. The rich need to be shown what life and death are like in the gutters. (Evil)",
				"People. I help the people who help me — that's what keeps us alive. (Neutral)",
				"Aspiration. I'm going to prove that I'm worthy of a better life.",
			],
			"bond": [
				"My town or city is my home, and I'll fight to defend it.",
				"I sponsor an orphanage to keep others from enduring what I was forced to endure.",
				"I owe my survival to another urchin who taught me to live on the streets.",
				"I owe a debt I can never repay to the person who took pity on me.",
				"I escaped my life of poverty by robbing an important person, and I'm wanted for it.",
				"No one else should have to endure the hardships I've been through.",
			],
			"flaw": [
				"If I'm outnumbered, I will run away from a fight.",
				"Gold seems like a lot of money to me, and I'll do just about anything for more of it.",
				"I will never fully trust anyone other than myself.",
				"I'd rather kill someone in their sleep then fight fair.",
				"It's not stealing if I need it more than someone else.",
				"People who can't take care of themselves get what they deserve.",
			],
		},
		"cook": {
			".": "1",
			"background": ["cook"],
			"desc": ["",],
			"specialty": [
				"Chef de Cuisine or Sous Chef, Manages the kitchen and its staff. The Chef de Cuisine is typically authorised to write and alter the menu, while a sous chef is just a manager.",
				"Chef de Partie, Manages a portion of the kitchen staff if the team is very large. Examples include Rôtisseur (roast cook), Entremetier (entrée preparer), and Pâtissier (pastry cook). If they do the work themselves, they are called a demi-chef.",
				"Cuisinier, An cook in an independent position which requires no team or division of oversight, so are generally superior to cuisiniers de parti, but subordinate to all chefs. Examples include, Saucier (saucemaker), Poissonnier (fishcook), Boucher (butcher), and Communard (Kitchen staff meal cook).",
				"Cuisinier de Parti, A subordinate to a chef in a particular area of the kitchen. The Grillardin (grill cook) and Friturier (fry cook) answer to the Rôtisseur. The Potager (soup cook) and Legumier (vegetable cook) answer to the Entremetier. The Confiseur (candy maker), Glacier (frozen desert maker), Décorateur (desert decorator), and Boulanger (baker) answer to the Pâtissier.",
				"Apprentice or Commis, Generally an assistant, they look after the cooking equipment, not the food. A successful apprentice becomes a commis, who eventually takes on higher responsibilities.",
				"Kitchen Staff, These positions deal with other tasks around the kitchen, and include the Garde Manger (pantry supervisor), Aboyeur (announcer/expediter), Tournant (spare hand/roundsman), Garçon de cuisine (kitchen boy), and Plongeur/Marmiton or Porter (dish/pot washer). All of these positions are known to be enlisted to do basic/menial food preparation. ",
			],
			"trait": [
				"My opinion is relevant - whether you like it or not.",
				"I multitask very well.",
				"I let others know I expect them to work as hard as I do.",
				"I make noises which indicate my mood when I eat.",
				"When insulted, I hurl even greater insults (or food) back.",
				"I like to take my time and savor each moment.",
				"I try to keep things as clean as possible.",
				"I am always on the lookout for something novel and exotic. ",
			],
			"ideal": [
				"Creativity. I don't even follow my own recipes, I just follow my gut instinct! (Chaotic)",
				"Knowledge. You can learn a lot about people from what they choose to eat. (Neutral)",
				"Hierarchy. I know my place. Know yours. (Lawful)",
				"Generosity. My gift is for all to enjoy! (Good)",
				"Community. I am just one contribution which keeps this society together (Neutral)",
				"Fame. I will be known as the greatest master chef for all time! (Any) ",
			],
			"bond": [
				"My grandmother had a secret recipe she took to her grave. I am trying to replicate it.",
				"There is a famous chef who I idolize.",
				"I am putting together a book of recipes from around the world!",
				"While other lands have vibrant cuisine, nothing beats a meal in the home country.",
				"I use only the elaborate techniques of my master, even when preparing simple dishes.",
				"I always keep a bottle of my favorite spice or herb on hand.",
			],
			"flaw": [
				"I'd rather eat nothing than something bland, stale, burnt, undercooked, or otherwise beneath me.",
				"I am comedically competetive.",
				"I am a gluttonous pig.",
				"I whine and complain when uncomfortable.",
				"I have little to no tolerance for frivolity.",
				"I have troubles trusting others with their assigned tasks, especially if I assigned them.",
			],
		},
		"keep": {
			".": "1",
			"background": ["keep"],
			"desc": ["",],
			"specialty": [
				"Man of Many Words - Because of the many patrons that pass through your bar you have picked up a few key phrases from other languages, you become proficient with one other standard language of your choice.",
				"Keen Eye - Many of your regulars have sticky fingers and so you have learned to notice the smaller movements, you gain proficiency in perception.",
				"Quick Draw - You've mastered card games to the point where you've started to implement some tricks into daily life, you gain proficiency in Sleight of hand.",
				"Sharp Tongue - Many fights have occurred in you inn to the point where it is exhausting, you've learned to resolve issues with words instead of weapons. You have proficiency in persuasion.",
				"Brawler - Fights occur in every bar and inn, to resolve this issue you decided to prepare for the next fight. You gain the tavern brawler feat.",
				"Ear to the Ground - Many adventures have wandered through your bar telling great tales and heroics, as well as lore, you gain profiency in history.",
			],
			"trait": [
				"Everyone has a story to tell, for the right price.",
				"In my books, if your a Patron, you're a friend.",
				"I've always believed that alcohol is the best medicine.",
				"I've never been scared to back down from a fight.",
				"My sharp wit and cunning remarks can cut tension like a hot knife.",
				"I have a joke for every occasion.",
				"I like to collect trinkets and magical objects, even if that means stealing them sometimes.",
				"I always have a story that relates to the matter at hand. ",
			],
			"ideal": [
				"Kindness: A smile and a free ale can raise a lot of spirits. (Good)",
				"Frugal: If I can haggle a price I will. (Lawful)",
				"Power: Gold can get you a lot, but a threat can get you more. (Evil)",
				"Curiosity: I'm always thinking of new concoctions to introduce to the inn. (Neutral)",
				"Knowledge: With enough alcohol, you can make someone tell you anything. (Chaotic)",
				"Freedom: if something is being given away, chances are, I will always take it. (Any) ",
			],
			"bond": [
				"I will always be grateful to my mentor who taught me everything I know.",
				"I remember being a \"gutter rat\" and will push for them to be treated equally.",
				"I am forever in debt to the family that adopted me when no one else would.",
				"A monster destoryed my village and family, and now it is my duty to slay the beast.",
				"I accidentally served a dangerous criminal and now the guards don't trust me.",
				"I have grown up fixing my families mistakes. ",
			],
			"flaw": [
				"I always speak my mind, for better or worse.",
				"I'm not the most careful of people and tend to break things now and again.",
				"I have a serious drinking problem.",
				"My wit has landed me in more jails than I can count.",
				"I tend to get carried away when insulting someone.",
				"My anger issues have been responsible for many broken jaws. ",
			],
		},
		"smith": {
			".": "1",
			"background": ["smith"],
			"desc": ["Metal workers are very personable, but also must be firm. They must deal with lots of people trying to pull a fast one on them and therefore tend to be a bit gritty. It takes a while to warm up to them, but once won over, metal workers are loyal friends for life. ",],
			"specialty": [
				"Weaponsmith. A type of smith who specializes in the craft of weapons. These metalworkers typically work in bronze, iron, or steel, though very early weaponsmiths worked in copper. Specialists include arrowsmiths, who craft arrowheads, and bladesmiths, who craft fine-edged tools.",
				"Armorer. A type of smith who specializes in the crafting of metal armor components, including rivots, buckles, studs, grommets, lames, chainmail, and even plate components.",
				"Metalsmith. Blacksmiths work ferrous metals, whitesmiths work tin or pewter, brassfounders work brass, coppersmiths work in copper, finesmiths work gold and silver. All of these craftsmen produce practical goods from their respective material expertise, from tools, to furniture, to ornaments, to jewelry.",
				"Mintner. A metalsmith in the direct employ of a sovereign state, authorized in the minting of currency in the form of coinage.",
				"Metallurgist. A metal-chemist who specializes in mixing base-metals and other chemicals to produce alloys, and treating metals to produce different grades of the same material with unique porperties.",
				"Smelter. Works in a smeltshop, operating a smelting furnace. You take raw ores, crush them into powder, and heat them with mixed chemical agents such as flux, until the metals inside melt, allowing the metal to be separated from its gangue. This raw metal is then cast into a preform called an ingot, billot, or bar.",
				"Founder. Works in a foundry, pouring metal positives from molds. Most castings are raw shapes which are then forged into something useful by a smith, like iron bars, but some goods are made directly as a casting, such as cast-iron cookware, anchors, ballast, or anvils.",
				"Machinist. A metalworker supremely skilled in the technical labor of metal finishing in practical applications, typically in the creation and maintenance of machines.",
			],
			"trait": [
				"I make light of violence and death.",
				"Sometimes I pretend to be uneducated to avoid uninteresting conversation.",
				"I have a crude sense of humor.",
				"I’m always trying to find the best deal possible, even for the smallest of trinkets.",
				"I grew up lonely and isolated, so people skills aren't really my thing.",
				"Sarcasm and insults are my true weapons of choice.",
				"I'm never too far from a tavern or a good time.",
				"I am always ready to fight. ",
			],
			"ideal": [
				"Fairness. I never offer overpriced goods to people who can’t afford to lose a few coins. (Lawful)",
				"Generosity. My talents were given to me so that I could use them to benefit the world. (Good)",
				"Authority. I do as I wish- who's going to stop me? (chaotic)",
				"Greed. I’m only in it for the money. (Evil)",
				"People. I’m committed to my comrades, not to ideals. (Neutral)",
				"Aspiration. I work hard to be the best there is at my craft. (Any) ",
			],
			"bond": [
				"The workshop where I learned my trade is the most important place in the world to me.",
				"I created a great work for someone, and then found them unworthy to receive it. I’m still looking for someone worthy.",
				"One day I will return to my forge and prove that I am the greatest artisan of them all.",
				"I strive to pay back my metal working mentor for forging me into the person I am today.",
				"Someone stole one of my most prized creations. One day, I will make them pay.",
				"My weapons were once used for evil purposes. Never again will someone take advantage of me. ",
			],
			"flaw": [
				"I find any reason to fight, often attacking enemies when other solutions could have been met.",
				"I care more about my weapon, armor, or other possession, than I do about my friends.",
				"I’m quick to assume that someone is trying to cheat me.",
				"I’m horribly jealous of anyone who can outshine my handiwork. Everywhere I go, I’m surrounded by rivals.",
				"No one must ever learn that I once ripped off a noble family for my own gain.",
				"I’ m never satisfied with what I have— I always want more. ",
			],
		},
	},
};
